### ISSUE TITLE
Timestamps of words seems not correct in file transcription service

### ISSUE THREAD

**Issue by electroniccc** [alibaba-damo-academy/FunASR#1169]
When I try to convert some audio files, I notice that the timestamps in the returned result don't look correct. For example, the total duration of the audio file is about **6 minutes**, but the timestamp of the last word is about **600s**.
The file info:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/37819493/5f2d3b9e-9875-4d0a-b0c7-628a2c24609f)
The result:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/37819493/b5f4fbfb-7785-41fb-8e0f-290e72096b80)

My enviroment:
OS: Ubuntu22.04(WSL)
Docker image:
```bash
a186f040b0a1   registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.3.0   "/bin/bash"   3 weeks ago   Up 30 seconds             0.0.0.0:10095->10095/tcp   funasr
```
Start command:
```bash
nohup bash run_server.sh \
  --certfile "" \
  --model_dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx \
  > log.out 2>&1 &
```

The sample file: [https://drive.google.com/file/d/1YS3gWovNJIPDjN9gs-vBxoNx7dUvvO2l/view?usp=drive_link](https://drive.google.com/file/d/1YS3gWovNJIPDjN9gs-vBxoNx7dUvvO2l/view?usp=drive_link)

**Comment by lyblsgo** [comment]
Currently, after passing through the ITN, timestamp misalignment occurs. The issue has been fixed and will be released in the next version.

**Comment by lyblsgo** [comment]
try funasr:funasr-runtime-sdk-cpu-0.4.0

**Comment by electroniccc** [comment]
Tried **funasr-runtime-sdk-cpu-0.4.2**, the issue still exists.

**Comment by lyblsgo** [comment]
If the issue persists, please provide detailed steps to reproduce, as well as server and client logs.

**Comment by wincing2** [comment]
> Currently, after passing through the ITN, timestamp misalignment occurs. The issue has been fixed and will be released in the next version.

The issue mentioned by the poster doesn't happen when doing ASR via python inference though:
```
model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                  model_revision="v2.0.4",
                  )
res = model.generate(input=wavf)
```
But I did find some misalignment cases where some sentences within a long audio mis-align by around 0.5s by using the above python code. Is it possible that the ITN issue you mentioned is responsible for this?
