### ISSUE TITLE
h5网页文件时长限制

### ISSUE THREAD

**Issue by hufeidashuai** [alibaba-damo-academy/FunASR#1502]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
在h5网页上上传超过1分钟的音频，就推理失败。（一分钟音频可以，超过一秒就不行，感觉像是websocket没回传到后端）。
#### What's your environment?
 - OS (e.g., Linux):Linux or windows
 - FunASR Version (e.g., 1.0.0):1.0.0
 - ModelScope Version (e.g., 1.11.0):1.11.1
 - PyTorch Version (e.g., 2.0.0):2.0.0
 - How you installed funasr (`pip`, source):pip
 - Python version:3.8.10
 - GPU (None)

**Comment by LauraGPT** [comment]
Bug has been fixed. https://github.com/alibaba-damo-academy/FunASR/commit/b32b21d9c8b0ea659711760e7c80fb572d6b7a41

**Comment by hufeidashuai** [comment]
I think this problem is not solved yet. I can display the results using audio files of one minute or less, but no results are displayed for audio files longer than one minute.

**Comment by hufeidashuai** [comment]
[output.zip](https://github.com/alibaba-damo-academy/FunASR/files/14648645/output.zip)
This is a test file with one minute of audio and more than one minute of audio.

**Comment by zhaomingwork** [comment]
> [output.zip](https://github.com/alibaba-damo-academy/FunASR/files/14648645/output.zip) This is a test file with one minute of audio and more than one minute of audio.

both files seem just one minite in length when open with Audition. upload more examples.

**Comment by hufeidashuai** [comment]
[out.zip](https://github.com/alibaba-damo-academy/FunASR/files/14661066/out.zip)
Uploaded again, with an additional audio of about five minutes.

**Comment by dantecsm** [comment]
same here, any proper solution?
